"""
Instructions:
Write a program that generates a random number in a range of 1 through 100, 
and asks the user to quess the number. It should then tell the user wether 
the quess is correct, too high or too low. If the number is quessed, a new game begins."""

import random

def numberQuesser():
    print("Welcome to numberQuesser!\nIn this game, you must quess the number generated by the computer. \nIt will be between 1 and 100.")
    number = random.randint(1, 100)
    quess = int(input("Quess a number between 1 and 100: "))
    tries = 0
    while number != quess:
        tries += 1
        if quess > number:
            quess = int(input("Too high, try again: "))
        else: 
            quess = int(input("Too low, try again: "))
    print("Congratulations, you got the number!\nIt took you", tries, "wrong quesses.")
    again = input("Type 'yes' if you wish to play again ")
    if again == "yes":
        numberQuesser()
    else:
        print("Bye!")

numberQuesser()